version: "3.9"

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    networks:
      macvlan_net:
        # Assign your dedicated IP address here
        ipv4_address: 192.168.50.250
        ipv6_address: fd15:d91c:273f:0::250
      cloudflare:
    volumes:
      - adguard_work:/opt/adguardhome/work
      - adguard_config:/opt/adguardhome/conf

networks:
  macvlan_net:
    driver: macvlan
    enable_ipv6: true
    driver_opts:
      # run ip route | grep default on your host to find the correct parent interface
      parent: ens18 
    ipam:
      config:
        # Change these to match your router and network
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.1
        # run ip -6 addr show dev ens18 on your host to find the correct IPv6 subnet and gateway
        - subnet: fd15:d91c:273f:0::/64
          gateway: fd15:d91c:273f:0::1
  cloudflare:
    external: true

volumes:
  adguard_config:
    external: true
  adguard_work:
    external: true
