version: "3.9"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    networks: [cloudflare]
    ports:
      - "3000:3000"
      - "2222:2222"
    volumes:
      - /var/lib/docker/volumes/infra_volume/_data/gitea_data:/data

  runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    restart: always
    depends_on: [gitea]
    networks: [cloudflare]
    environment:
      GITEA_RUNNER_NAME: CI-Runner
      CONFIG_FILE: /data/config.yaml
      GITEA_INSTANCE_URL: http://gitea:3000
      GITEA_RUNNER_TOKEN_FILE: /run/secrets/gitea_runner_token
      GITEA_RUNNER_LABELS: "prd,tst,docker,ubuntu-latest"
    volumes:
      - /var/lib/docker/volumes/infra_volume/_data/runner_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: ["/bin/sh", "/resolve-secrets.sh", "/sbin/tini", "--", "run.sh"]
    secrets:
      - source: gitea_runner_token
        uid: "1000"
        gid: "1000"
        mode: 0400
    configs:
      - source: act_runner_config
        target: /data/config.yaml
      - source: resolve_secrets_script
        target: /resolve-secrets.sh
        mode: 0555

networks:
  cloudflare:
    external: true

secrets:
  gitea_runner_token:
    file: /data/compose/secrets/gitea/gitea_runner_token

configs:
  act_runner_config:
    content: |
      log:
        level: info

      runner:
        file: .runner
        capacity: 4
        timeout: 3h
        labels:
          - "ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest"

      container:
        network: cloudflare
        valid_volumes:
            - "howtolosemoney-content-dev"
            - "howtolosemoney-content-prd"
            - "gitea-build-data"
            - "portfoliomanager-content-dev"
            - "portfoliomanager-content-prd"
            - "blog-astro-content-prd"
  resolve_secrets_script:
    file: ./scripts/resolve-secrets.sh
