version: "3.8"

services:
  nas-manager-hooks:
    build:
      context: ./nas-manager
    image: diecklabs/nas-manager:latest
    container_name: nas-manager-hooks
    ports:
      - "9000:9000"
    volumes:
      - dyndns-data:/var/lib/dyndns
    restart: unless-stopped

volumes:
  dyndns-data:
