version: "3.8"

services:
  nas-manager-hooks:
    image: almir/webhook:latest
    container_name: nas-manager-hooks
    user: "0:0"
    ports:
      - "9000:9000"
    volumes:
      - dyndns-data:/var/lib/dyndns
      - ./nas-manager/webhook:/etc/webhook:ro
      - ./nas-manager/scripts:/scripts:ro
    secrets:
      - source: cf_auth_token
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: cf_account_id
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: cf_policy_id
        uid: "1000"
        gid: "1000"
        mode: 0400
    entrypoint:
      - /bin/sh
      - -ec
      - |
        set -eu
        export CF_AUTH_TOKEN="$(cat /run/secrets/cf_auth_token)"
        export CF_ACCOUNT_ID="$(cat /run/secrets/cf_account_id)"
        export CF_POLICY_ID="$(cat /run/secrets/cf_policy_id)"
        exec /usr/local/bin/webhook -verbose -hooks=/etc/webhook/hooks.json -hotreload
    restart: unless-stopped
    networks:
      - ipv6network

networks:
  ipv6network:
    external: true

secrets:
  cf_auth_token:
    file: /opt/portainer_iac/secrets/secrets/hooks/cloudflare_auth_token
  cf_account_id:
    file: /opt/portainer_iac/secrets/secrets/hooks/cloudflare_account_id
  cf_policy_id:
    file: /opt/portainer_iac/secrets/secrets/hooks/cloudflare_policy_id

volumes:
  dyndns-data:
