version: "3.8"

services:
  nas-manager-hooks:
    build:
      context: ./nas-manager
    image: diecklabs/nas-manager:latest
    container_name: nas-manager-hooks
    ports:
      - "9000:9000"
    volumes:
      - dyndns-data:/var/lib/dyndns
    configs:
      - source: resolve_secrets_script
        target: /scripts/resolve-secrets.sh
        mode: 0555
    secrets:
      - source: cf_auth_token
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: cf_account_id
        uid: "1000"
        gid: "1000"
        mode: 0400
      - source: cf_policy_id
        uid: "1000"
        gid: "1000"
        mode: 0400
    environment:
      CF_AUTH_TOKEN_FILE: /run/secrets/cf_auth_token
      CF_ACCOUNT_ID_FILE: /run/secrets/cf_account_id
      CF_POLICY_ID_FILE: /run/secrets/cf_policy_id
    restart: unless-stopped
    networks:
      - ipv6network

networks:
  ipv6network:
    external: true

secrets:
  cf_auth_token:
    file: /opt/portainer_iac/secrets/secrets/hooks/cloudflare_auth_token
  cf_account_id:
    file: /opt/portainer_iac/secrets/secrets/hooks/cloudflare_account_id
  cf_policy_id:
    file: /opt/portainer_iac/secrets/secrets/hooks/cloudflare_policy_id

volumes:
  dyndns-data:

configs:
  resolve_secrets_script:
    file: ./scripts/resolve-secrets.sh
