version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - cloudflare
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - /mnt/media/video:/media/video:ro
    ports:
      - "8096:8096"

networks:
  cloudflare:
    external: true

volumes:
  jellyfin_config:
    external: true
  jellyfin_cache:
    external: true
