version: "3.9"

services:
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cf-tunnel
    restart: always
    command: tunnel --no-autoupdate run --token-file /run/secrets/cf_tunnel_token
    networks:
      - cloudflare
    secrets:
      - cf_tunnel_token

networks:
  cloudflare:
    external: true

secrets:
  cf_tunnel_token:
    file: ./secrets/secrets/tunnel/token
