{
 "title": "Ubuntu SSH Logs (Journald)",
 "description": "Ubuntu Systemd-Journal SSH Logs",
 "tags": [
  "loki",
  "linux",
  "ssh",
  "ubuntu"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "loki" },
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "SSH - Total Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Opened Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\"session opened for\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Failed Connection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (count_over_time({job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\"(?i)Failed|Invalid|Connection closed\" | __error__=\"\" [$__interval]))"
    }
   ]
  },
  {
   "title": "Total Failed - Unique IP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "count by (ip) (count_over_time({job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\"(?i)Failed|Invalid|Connection closed\" | regexp \"(?i)(from |user [^ ]+ )(?P<ip>[a-f0-9\\\\.:]+) port\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "SSH Log Lines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} | __error__=\"\" [$__interval])"
    }
   ]
  },
  {
   "title": "Session Opened by User",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (username) (count_over_time({job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\"session opened for\" | regexp \"user (?P<username>[^ \\\\(]+)\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  {
   "title": "Failed Attempt by User",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (username) (count_over_time({job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\"(?i)Failed|Invalid|Connection closed\" | regexp \"(?i)(user |for )(?P<username>[^ \\\\(]+)\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ username }}"
    }
   ]
  },
  {
   "title": "SSH Recent Log",
   "type": "logs",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"}"
    }
   ]
  },
  {
   "title": "Session Opened by Unique IP",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count by (ip) (count_over_time({job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\"Accepted\" | regexp \"(?i)from (?P<ip>[a-f0-9\\\\.:]+) port\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Failed by Unique IP",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "count by (ip) (count_over_time({job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\"(?i)Failed|Invalid|Connection closed\" | regexp \"(?i)(from |user [^ ]+ )(?P<ip>[a-f0-9\\\\.:]+) port\" | __error__=\"\" [$__interval]))",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  { "title": "Detailed Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Session Opened by User and IP",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |=\"Accepted\" | regexp \"(?i)for (?P<username>[^ ]+) from (?P<ip>[a-f0-9\\\\.:]+) port\" | __error__=\"\""
    }
   ]
  },
  {
   "title": "SSH Failure by User and IP",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "{job=~\"$job\", instance=~\"$instance\", syslog_identifier=\"sshd\"} |~\"(?i)Failed|Invalid|Connection closed\" | regexp \"(?i)(user |for )(?P<username>[^ ]+) (from |)(?P<ip>[a-f0-9\\\\.:]+) port\" | __error__=\"\""
    }
   ]
  }
 ]
}